language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  # Build/test dependencies
  - pip install -r requirements.txt
script:
  - nosetests
branches:
  only:
    - develop